# Generated by Django 5.0.6 on 2024-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrineSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="samples/")),
                ("result", models.TextField(blank=True, max_length=500)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
